// <auto-generated />
using System;
using DiveDeep.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiveDeep.Migrations
{
    [DbContext(typeof(DiveDeepContext))]
    [Migration("20260908124055_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiveDeep.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingId");

                    b.HasIndex("ProductId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DiveDeep.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PricePerDay")
                        .HasColumnType("real");

                    b.HasKey("ProductId");

                    b.ToTable("Products", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DiveDeep.Models.BCD", b =>
                {
                    b.HasBaseType("DiveDeep.Models.Product");

                    b.PrimitiveCollection<string>("Sizes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("BCDs", (string)null);
                });

            modelBuilder.Entity("DiveDeep.Models.DiveSuit", b =>
                {
                    b.HasBaseType("DiveDeep.Models.Product");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Sizes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("SuitTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thickness")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DiveSuits", (string)null);
                });

            modelBuilder.Entity("DiveDeep.Models.Fins", b =>
                {
                    b.HasBaseType("DiveDeep.Models.Product");

                    b.PrimitiveCollection<string>("Sizes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Fins", (string)null);
                });

            modelBuilder.Entity("DiveDeep.Models.MaskSnorkel", b =>
                {
                    b.HasBaseType("DiveDeep.Models.Product");

                    b.PrimitiveCollection<string>("Sizes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("MAskSnorkels", (string)null);
                });

            modelBuilder.Entity("DiveDeep.Models.RegulatorSet", b =>
                {
                    b.HasBaseType("DiveDeep.Models.Product");

                    b.Property<string>("FirstStep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Octopus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondStep")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("RegulatorSets", (string)null);
                });

            modelBuilder.Entity("DiveDeep.Models.Tank", b =>
                {
                    b.HasBaseType("DiveDeep.Models.Product");

                    b.PrimitiveCollection<string>("Sizes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Tanks", (string)null);
                });

            modelBuilder.Entity("DiveDeep.Models.Booking", b =>
                {
                    b.HasOne("DiveDeep.Models.Product", "Product")
                        .WithMany("Bookings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiveDeep.Models.BCD", b =>
                {
                    b.HasOne("DiveDeep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeep.Models.BCD", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeep.Models.DiveSuit", b =>
                {
                    b.HasOne("DiveDeep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeep.Models.DiveSuit", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeep.Models.Fins", b =>
                {
                    b.HasOne("DiveDeep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeep.Models.Fins", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeep.Models.MaskSnorkel", b =>
                {
                    b.HasOne("DiveDeep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeep.Models.MaskSnorkel", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeep.Models.RegulatorSet", b =>
                {
                    b.HasOne("DiveDeep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeep.Models.RegulatorSet", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeep.Models.Tank", b =>
                {
                    b.HasOne("DiveDeep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeep.Models.Tank", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeep.Models.Product", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
