// <auto-generated />
using System;
using DiveDeep.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiveDeep.Migrations
{
    [DbContext(typeof(DiveDeepContext))]
    partial class DiveDeepContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiveDeep.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int?>("BundleBookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingId");

                    b.HasIndex("BundleBookingId");

                    b.HasIndex("ProductId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DiveDeep.Models.BundleBooking", b =>
                {
                    b.Property<int>("BundleBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BundleBookingId"));

                    b.Property<int>("BundleId")
                        .HasColumnType("int");

                    b.Property<string>("BundleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("DiscountPercent")
                        .HasColumnType("real");

                    b.HasKey("BundleBookingId");

                    b.ToTable("BundleBookings");
                });

            modelBuilder.Entity("DiveDeep.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PricePerDay")
                        .HasColumnType("real");

                    b.HasKey("ProductId");

                    b.ToTable("Products", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DiveDeep.Models.BCD", b =>
                {
                    b.HasBaseType("DiveDeep.Models.Product");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.ToTable("BCDs", (string)null);
                });

            modelBuilder.Entity("DiveDeep.Models.DiveSuit", b =>
                {
                    b.HasBaseType("DiveDeep.Models.Product");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("SuitType")
                        .HasColumnType("int");

                    b.Property<string>("Thickness")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DiveSuits", (string)null);
                });

            modelBuilder.Entity("DiveDeep.Models.Fins", b =>
                {
                    b.HasBaseType("DiveDeep.Models.Product");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.ToTable("Fins", (string)null);
                });

            modelBuilder.Entity("DiveDeep.Models.MaskSnorkel", b =>
                {
                    b.HasBaseType("DiveDeep.Models.Product");

                    b.ToTable("MaskSnorkels", (string)null);
                });

            modelBuilder.Entity("DiveDeep.Models.RegulatorSet", b =>
                {
                    b.HasBaseType("DiveDeep.Models.Product");

                    b.Property<string>("FirstStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Octopus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("RegulatorSets", (string)null);
                });

            modelBuilder.Entity("DiveDeep.Models.Tank", b =>
                {
                    b.HasBaseType("DiveDeep.Models.Product");

                    b.Property<int>("VolumeLiters")
                        .HasColumnType("int");

                    b.ToTable("Tanks", (string)null);
                });

            modelBuilder.Entity("DiveDeep.Models.Booking", b =>
                {
                    b.HasOne("DiveDeep.Models.BundleBooking", "BundleBooking")
                        .WithMany("Bookings")
                        .HasForeignKey("BundleBookingId");

                    b.HasOne("DiveDeep.Models.Product", "Product")
                        .WithMany("Bookings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BundleBooking");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiveDeep.Models.BCD", b =>
                {
                    b.HasOne("DiveDeep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeep.Models.BCD", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeep.Models.DiveSuit", b =>
                {
                    b.HasOne("DiveDeep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeep.Models.DiveSuit", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeep.Models.Fins", b =>
                {
                    b.HasOne("DiveDeep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeep.Models.Fins", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeep.Models.MaskSnorkel", b =>
                {
                    b.HasOne("DiveDeep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeep.Models.MaskSnorkel", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeep.Models.RegulatorSet", b =>
                {
                    b.HasOne("DiveDeep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeep.Models.RegulatorSet", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeep.Models.Tank", b =>
                {
                    b.HasOne("DiveDeep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeep.Models.Tank", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeep.Models.BundleBooking", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DiveDeep.Models.Product", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
